# Generated by Django 2.0.7 on 2018-10-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_cita', models.DateTimeField()),
                ('asunto', models.CharField(max_length=200)),
                ('observaciones', models.TextField()),
                ('estatus', models.CharField(choices=[('1', 'Solicitada'), ('2', 'Aceptada'), ('3', 'Atendida')], default='1', max_length=2)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
