# Generated by Django 2.0.7 on 2018-10-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20181021_1911'),
        ('incidencia', '0003_auto_20181021_1918'),
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaIncidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.ManyToManyField(blank=True, to='cita.Cita')),
                ('incidencia', models.ManyToManyField(blank=True, to='incidencia.Incidencia')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.ManyToManyField(blank=True, to='cita.Comentario')),
                ('persona', models.ManyToManyField(blank=True, to='usuario.Docente')),
                ('rel', models.ManyToManyField(blank=True, to='cita.Cita')),
            ],
        ),
    ]
