# Generated by Django 2.0.7 on 2018-10-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_citaincidencia_comentario_comentariorel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citaincidencia',
            name='cita',
            field=models.ManyToManyField(to='cita.Cita'),
        ),
        migrations.AlterField(
            model_name='citaincidencia',
            name='incidencia',
            field=models.ManyToManyField(to='incidencia.Incidencia'),
        ),
    ]
