# Generated by Django 2.0.7 on 2018-11-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_auto_20181028_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='cita',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
