# Generated by Django 2.0.7 on 2018-10-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='H', max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('matricula', models.CharField(help_text='Matricula del alumno', max_length=8, primary_key=True, serialize=False, unique=True)),
                ('grado', models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero')], default='1', max_length=10)),
                ('grupo', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=10)),
            ],
        ),
    ]
