# Generated by Django 2.0.7 on 2018-09-09 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('matricula', models.CharField(help_text='Matricula del alumno', max_length=8, primary_key=True, serialize=False)),
                ('grado', models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero')], default='1', max_length=10)),
                ('grupo', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.CharField(choices=[('1', 'Si'), ('2', 'No'), ('3', 'Temporal')], default='1', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PadreAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ManyToManyField(to='usuario.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='PadreFamilia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_nacimiento', models.DateField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_persona', models.CharField(choices=[('1', 'Administrador'), ('2', 'Docente'), ('3', 'Padre de familia'), ('4', 'Alumno')], default='4', max_length=2)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='H', max_length=1)),
                ('token', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('contra', models.CharField(max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='padrefamilia',
            name='padre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Persona'),
        ),
        migrations.AddField(
            model_name='padrealumno',
            name='padre',
            field=models.ManyToManyField(to='usuario.PadreFamilia'),
        ),
        migrations.AddField(
            model_name='docente',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Persona'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Persona'),
        ),
    ]
