# Generated by Django 2.0.7 on 2018-10-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0002_auto_20181021_1911'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.AlterField(
            model_name='padrealumno',
            name='alumno',
            field=models.ManyToManyField(to='alumno.Alumno'),
        ),
    ]
