# Generated by Django 2.0.7 on 2018-09-10 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20180909_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='nombre_usuario',
        ),
    ]
