# Generated by Django 2.0.7 on 2018-09-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20180916_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='0123456789', max_length=10),
            preserve_default=False,
        ),
    ]
