# Generated by Django 2.0.7 on 2018-09-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0002_remove_incidenciapadre_padre'),
        ('usuario', '0005_auto_20180916_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padrefamilia',
            name='padre',
        ),
        migrations.AlterField(
            model_name='padrealumno',
            name='padre',
            field=models.ManyToManyField(to='usuario.Persona'),
        ),
        migrations.DeleteModel(
            name='PadreFamilia',
        ),
    ]
