# Generated by Django 2.0.7 on 2018-08-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20180729_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='doncente',
            new_name='docente',
        ),
        migrations.AlterField(
            model_name='docente',
            name='tutor',
            field=models.CharField(choices=[('1', 'Si'), ('2', 'No'), ('3', 'Temporal')], default='1', max_length=5),
        ),
    ]
