# Generated by Django 2.0.7 on 2018-09-17 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20180916_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contra',
        ),
    ]
