# Generated by Django 2.0.7 on 2018-09-17 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_remove_usuario_contra'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadreFam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Persona')),
            ],
        ),
        migrations.AlterField(
            model_name='padrealumno',
            name='padre',
            field=models.ManyToManyField(to='usuario.PadreFam'),
        ),
    ]
