# Generated by Django 2.0.7 on 2018-09-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_auto_20180810_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='grado',
            field=models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='grupo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='H', max_length=1),
        ),
    ]
