# Generated by Django 2.0.7 on 2018-10-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_auto_20181021_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
