# Generated by Django 2.0.7 on 2018-09-26 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_auto_20180926_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
    ]
