# Generated by Django 2.0.7 on 2018-10-22 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_auto_20181021_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
    ]
