# Generated by Django 2.0.7 on 2018-10-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_remove_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='grupo',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='tutor',
            field=models.CharField(choices=[('1', 'Si'), ('2', 'No')], default='1', max_length=5),
        ),
    ]
