# Generated by Django 2.0.7 on 2018-10-22 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.ManyToManyField(blank=True, to='incidencia.Comentario')),
                ('persona', models.ManyToManyField(blank=True, to='usuario.Docente')),
                ('rel', models.ManyToManyField(blank=True, to='cita.Cita')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id_incidencia', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_incidencia', models.DateTimeField()),
                ('estatus', models.CharField(choices=[('1', 'Reportada'), ('2', 'En Proceso'), ('3', 'Atendida'), ('4', 'Otro')], default='1', max_length=2)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciaAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ManyToManyField(blank=True, to='usuario.Alumno')),
                ('incidencia', models.ManyToManyField(blank=True, to='incidencia.Incidencia')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciaCita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.ManyToManyField(blank=True, to='cita.Cita')),
                ('incidencia', models.ManyToManyField(blank=True, to='incidencia.Incidencia')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciaDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.ManyToManyField(blank=True, to='usuario.Docente')),
                ('incidencia', models.ManyToManyField(blank=True, to='incidencia.Incidencia')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciaPadre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidencia', models.ManyToManyField(blank=True, to='incidencia.Incidencia')),
            ],
        ),
        migrations.CreateModel(
            name='TipoIndicencia',
            fields=[
                ('id_tipo', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=200)),
                ('tipo', models.CharField(choices=[('1', 'Administrativa'), ('2', 'Conducta'), ('3', 'Labor'), ('4', 'Otro')], default='1', max_length=2)),
                ('impacto', models.CharField(choices=[('1', 'Leve'), ('2', 'Moderado'), ('3', 'Grabe')], default='1', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='incidencia',
            name='incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencia.TipoIndicencia'),
        ),
    ]
