# Generated by Django 2.0.7 on 2018-10-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenciaalumno',
            name='alumno',
            field=models.ManyToManyField(blank=True, to='alumno.Alumno'),
        ),
    ]
