# Generated by Django 2.0.7 on 2018-10-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0002_remove_incidenciapadre_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoindicencia',
            name='tipo',
            field=models.CharField(choices=[('1', 'Administrativa'), ('2', 'Conducta'), ('3', 'Labor'), ('4', 'Otro')], default='1', max_length=2),
        ),
    ]
