# Generated by Django 2.0.7 on 2018-10-22 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0002_auto_20181021_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentariorel',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='comentariorel',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='comentariorel',
            name='rel',
        ),
        migrations.RemoveField(
            model_name='incidenciacita',
            name='cita',
        ),
        migrations.RemoveField(
            model_name='incidenciacita',
            name='incidencia',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='ComentarioRel',
        ),
        migrations.DeleteModel(
            name='IncidenciaCita',
        ),
    ]
