# Generated by Django 2.0.7 on 2018-11-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0003_auto_20181021_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoindicencia',
            options={'ordering': ('tipo',)},
        ),
        migrations.AlterField(
            model_name='incidenciaalumno',
            name='alumno',
            field=models.ManyToManyField(to='alumno.Alumno'),
        ),
        migrations.AlterField(
            model_name='incidenciaalumno',
            name='incidencia',
            field=models.ManyToManyField(to='incidencia.Incidencia'),
        ),
    ]
