# Generated by Django 2.0.7 on 2018-10-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0003_auto_20181002_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoindicencia',
            name='impacto',
            field=models.CharField(choices=[('1', 'Leve'), ('2', 'Moderado'), ('3', 'Grabe')], default='1', max_length=10),
        ),
    ]
