# Generated by Django 2.0.7 on 2018-11-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0004_auto_20181103_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='estatus',
            field=models.CharField(choices=[('1', 'Reportada'), ('2', 'En Proceso'), ('3', 'Atendida')], default='1', max_length=2),
        ),
    ]
