# Generated by Django 2.0.7 on 2018-10-08 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0004_auto_20181007_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidencia',
            old_name='tipo',
            new_name='incidencia',
        ),
    ]
