# Generated by Django 2.0.7 on 2018-10-08 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0005_auto_20181007_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencia.TipoIndicencia'),
        ),
    ]
