# Generated by Django 2.0.7 on 2018-10-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0008_auto_20181007_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
