# Generated by Django 2.0.7 on 2018-10-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asunto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('tipo_persona', models.CharField(choices=[('1', 'Administrador'), ('2', 'Docente'), ('3', 'Padre de familia')], max_length=2)),
                ('grupo', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=10, null=True)),
                ('grado', models.CharField(blank=True, choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero')], max_length=10, null=True)),
            ],
        ),
    ]
