# Generated by Django 2.0.7 on 2018-10-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
