# Generated by Django 2.0.7 on 2018-10-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20181030_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviso',
            name='tipo_persona',
        ),
        migrations.AddField(
            model_name='aviso',
            name='dirijido_a',
            field=models.CharField(choices=[('1', 'Todos'), ('2', 'Docentes'), ('3', 'Padres de familia')], default='1', max_length=2),
            preserve_default=False,
        ),
    ]
