# Generated by Django 2.0.7 on 2018-10-30 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20181030_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aviso',
            old_name='dirijido_a',
            new_name='dirigido_a',
        ),
    ]
