# Generated by Django 2.0.7 on 2018-11-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0002_auto_20181102_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiadocente',
            name='docente',
            field=models.ManyToManyField(to='usuario.Docente'),
        ),
    ]
