"""
Django settings for ProyectSecusoft project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'va+7ib=)o!0@8bc)cff+opxam*5tz2+9j4=ig0bz#9fdbmsly('

DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'rest_framework',
    'rest_framework.authtoken',
    'fcm_django',
    'usuario',
    'cita',
    'incidencia',
    'dashboard',
    'materia',
    'alumno',
]

AUTH_USER_MODEL = 'usuario.Usuario'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ProyectSecusoft.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ProyectSecusoft.wsgi.application'

FCM_DJANGO_SETTINGS = {
        "FCM_SERVER_KEY": "AAAA_lSd86I:APA91bEoyKsCv9deYH2YuK_zP6TjcalZlG7Q_tP1BUuVByodAUQMPwJj7Dv2EGqBGlhfPLUkeyD17iwvWctfqTwp7K2TSeMqzlJj5548K1s5CRZE6lwqTqM0ISzK0eCQwj542YBRxQum",
        "ONE_DEVICE_PER_USER": False,
        "DELETE_INACTIVE_DEVICES": False,
}

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework.authentication.TokenAuthentication',
#     ),
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.IsAuthenticated',
#     ),
# }

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'smacsoft_secusoft',
#         'USER': 'RPSadmin',
#         'PASSWORD': 'k0rak11100293',
#         'HOST': 'mysql.s404.sureserver.com',
#
#     }
# }
#DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.mysql',
#             'NAME': 'Secusoft$default',
#             'USER': 'Secusoft',
#             'PASSWORD': 'hola1234',
#             'HOST': '127.0.0.1',
#         }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'secusoft2',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'CHARSET': 'utf8',
        'COLLATION': 'utf8_general_ci',
    }
}
# DATABASES ={'default': {'ATOMIC_REQUESTS': False,
#              'AUTOCOMMIT': True,
#              'CONN_MAX_AGE': 0,
#              'ENGINE': 'django.db.backends.mysql',
#              'HOST': 'Secusoft.mysql.pythonanywhere-services.com',
#              'NAME': 'Secusoft$default',
#              'OPTIONS': {},
#              'PASSWORD': 'hola1234',
#              'PORT': '',
#              'TEST': {'CHARSET': None,
#                       'COLLATION': None,
#                       'MIRROR': None,
#                       'NAME': None},
#              'TIME_ZONE': None,
#              'USER': 'Secusoft'}}
# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators
DATABASES['default']['OPTIONS'] = {"init_command": "SET foreign_key_checks = 0;"}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'es_MX'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# EMAIL_HOST = 'localhost'
# EMAIL_PORT = 1025

FILE_UPLOAD_HANDLERS = ("django_excel.ExcelMemoryFileUploadHandler",
                        "django_excel.TemporaryExcelFileUploadHandler")

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'secusoft.no.reply@gmail.com'
EMAIL_HOST_PASSWORD = 'L0R3TO19'
EMAIL_PORT = 587
